#ifndef FILAGUI_RESOURCES_H_
#define FILAGUI_RESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t FILAGUI_RESOURCES_PACKAGE[];
    extern int FILAGUI_RESOURCES_UIBLIT_OFFSET;
    extern int FILAGUI_RESOURCES_UIBLIT_SIZE;
}
#define FILAGUI_RESOURCES_UIBLIT_DATA (FILAGUI_RESOURCES_PACKAGE + FILAGUI_RESOURCES_UIBLIT_OFFSET)

#endif
