#ifndef SHADERS_H_
#define SHADERS_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t SHADERS_PACKAGE[];
    extern int SHADERS_AMBIENT_OCCLUSION_FS_OFFSET;
    extern int SHADERS_AMBIENT_OCCLUSION_FS_SIZE;
    extern int SHADERS_BRDF_FS_OFFSET;
    extern int SHADERS_BRDF_FS_SIZE;
    extern int SHADERS_COMMON_GETTERS_FS_OFFSET;
    extern int SHADERS_COMMON_GETTERS_FS_SIZE;
    extern int SHADERS_COMMON_GRAPHICS_FS_OFFSET;
    extern int SHADERS_COMMON_GRAPHICS_FS_SIZE;
    extern int SHADERS_COMMON_LIGHTING_FS_OFFSET;
    extern int SHADERS_COMMON_LIGHTING_FS_SIZE;
    extern int SHADERS_COMMON_MATERIAL_FS_OFFSET;
    extern int SHADERS_COMMON_MATERIAL_FS_SIZE;
    extern int SHADERS_COMMON_MATH_FS_OFFSET;
    extern int SHADERS_COMMON_MATH_FS_SIZE;
    extern int SHADERS_COMMON_SHADING_FS_OFFSET;
    extern int SHADERS_COMMON_SHADING_FS_SIZE;
    extern int SHADERS_COMMON_SHADOWING_FS_OFFSET;
    extern int SHADERS_COMMON_SHADOWING_FS_SIZE;
    extern int SHADERS_COMMON_TYPES_FS_OFFSET;
    extern int SHADERS_COMMON_TYPES_FS_SIZE;
    extern int SHADERS_DEPTH_MAIN_FS_OFFSET;
    extern int SHADERS_DEPTH_MAIN_FS_SIZE;
    extern int SHADERS_DEPTH_MAIN_VS_OFFSET;
    extern int SHADERS_DEPTH_MAIN_VS_SIZE;
    extern int SHADERS_FOG_FS_OFFSET;
    extern int SHADERS_FOG_FS_SIZE;
    extern int SHADERS_GETTERS_FS_OFFSET;
    extern int SHADERS_GETTERS_FS_SIZE;
    extern int SHADERS_GETTERS_VS_OFFSET;
    extern int SHADERS_GETTERS_VS_SIZE;
    extern int SHADERS_INPUTS_FS_OFFSET;
    extern int SHADERS_INPUTS_FS_SIZE;
    extern int SHADERS_INPUTS_VS_OFFSET;
    extern int SHADERS_INPUTS_VS_SIZE;
    extern int SHADERS_LIGHT_DIRECTIONAL_FS_OFFSET;
    extern int SHADERS_LIGHT_DIRECTIONAL_FS_SIZE;
    extern int SHADERS_LIGHT_INDIRECT_FS_OFFSET;
    extern int SHADERS_LIGHT_INDIRECT_FS_SIZE;
    extern int SHADERS_LIGHT_PUNCTUAL_FS_OFFSET;
    extern int SHADERS_LIGHT_PUNCTUAL_FS_SIZE;
    extern int SHADERS_MAIN_FS_OFFSET;
    extern int SHADERS_MAIN_FS_SIZE;
    extern int SHADERS_MAIN_VS_OFFSET;
    extern int SHADERS_MAIN_VS_SIZE;
    extern int SHADERS_MATERIAL_INPUTS_FS_OFFSET;
    extern int SHADERS_MATERIAL_INPUTS_FS_SIZE;
    extern int SHADERS_MATERIAL_INPUTS_VS_OFFSET;
    extern int SHADERS_MATERIAL_INPUTS_VS_SIZE;
    extern int SHADERS_POST_PROCESS_FS_OFFSET;
    extern int SHADERS_POST_PROCESS_FS_SIZE;
    extern int SHADERS_POST_PROCESS_VS_OFFSET;
    extern int SHADERS_POST_PROCESS_VS_SIZE;
    extern int SHADERS_POST_PROCESS_GETTERS_VS_OFFSET;
    extern int SHADERS_POST_PROCESS_GETTERS_VS_SIZE;
    extern int SHADERS_POST_PROCESS_INPUTS_FS_OFFSET;
    extern int SHADERS_POST_PROCESS_INPUTS_FS_SIZE;
    extern int SHADERS_POST_PROCESS_INPUTS_VS_OFFSET;
    extern int SHADERS_POST_PROCESS_INPUTS_VS_SIZE;
    extern int SHADERS_SHADING_LIT_FS_OFFSET;
    extern int SHADERS_SHADING_LIT_FS_SIZE;
    extern int SHADERS_SHADING_MODEL_CLOTH_FS_OFFSET;
    extern int SHADERS_SHADING_MODEL_CLOTH_FS_SIZE;
    extern int SHADERS_SHADING_MODEL_STANDARD_FS_OFFSET;
    extern int SHADERS_SHADING_MODEL_STANDARD_FS_SIZE;
    extern int SHADERS_SHADING_MODEL_SUBSURFACE_FS_OFFSET;
    extern int SHADERS_SHADING_MODEL_SUBSURFACE_FS_SIZE;
    extern int SHADERS_SHADING_PARAMETERS_FS_OFFSET;
    extern int SHADERS_SHADING_PARAMETERS_FS_SIZE;
    extern int SHADERS_SHADING_UNLIT_FS_OFFSET;
    extern int SHADERS_SHADING_UNLIT_FS_SIZE;
    extern int SHADERS_SHADOWING_FS_OFFSET;
    extern int SHADERS_SHADOWING_FS_SIZE;
    extern int SHADERS_VIGNETTE_FS_OFFSET;
    extern int SHADERS_VIGNETTE_FS_SIZE;
}
#define SHADERS_AMBIENT_OCCLUSION_FS_DATA (SHADERS_PACKAGE + SHADERS_AMBIENT_OCCLUSION_FS_OFFSET)
#define SHADERS_BRDF_FS_DATA (SHADERS_PACKAGE + SHADERS_BRDF_FS_OFFSET)
#define SHADERS_COMMON_GETTERS_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_GETTERS_FS_OFFSET)
#define SHADERS_COMMON_GRAPHICS_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_GRAPHICS_FS_OFFSET)
#define SHADERS_COMMON_LIGHTING_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_LIGHTING_FS_OFFSET)
#define SHADERS_COMMON_MATERIAL_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_MATERIAL_FS_OFFSET)
#define SHADERS_COMMON_MATH_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_MATH_FS_OFFSET)
#define SHADERS_COMMON_SHADING_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_SHADING_FS_OFFSET)
#define SHADERS_COMMON_SHADOWING_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_SHADOWING_FS_OFFSET)
#define SHADERS_COMMON_TYPES_FS_DATA (SHADERS_PACKAGE + SHADERS_COMMON_TYPES_FS_OFFSET)
#define SHADERS_DEPTH_MAIN_FS_DATA (SHADERS_PACKAGE + SHADERS_DEPTH_MAIN_FS_OFFSET)
#define SHADERS_DEPTH_MAIN_VS_DATA (SHADERS_PACKAGE + SHADERS_DEPTH_MAIN_VS_OFFSET)
#define SHADERS_FOG_FS_DATA (SHADERS_PACKAGE + SHADERS_FOG_FS_OFFSET)
#define SHADERS_GETTERS_FS_DATA (SHADERS_PACKAGE + SHADERS_GETTERS_FS_OFFSET)
#define SHADERS_GETTERS_VS_DATA (SHADERS_PACKAGE + SHADERS_GETTERS_VS_OFFSET)
#define SHADERS_INPUTS_FS_DATA (SHADERS_PACKAGE + SHADERS_INPUTS_FS_OFFSET)
#define SHADERS_INPUTS_VS_DATA (SHADERS_PACKAGE + SHADERS_INPUTS_VS_OFFSET)
#define SHADERS_LIGHT_DIRECTIONAL_FS_DATA (SHADERS_PACKAGE + SHADERS_LIGHT_DIRECTIONAL_FS_OFFSET)
#define SHADERS_LIGHT_INDIRECT_FS_DATA (SHADERS_PACKAGE + SHADERS_LIGHT_INDIRECT_FS_OFFSET)
#define SHADERS_LIGHT_PUNCTUAL_FS_DATA (SHADERS_PACKAGE + SHADERS_LIGHT_PUNCTUAL_FS_OFFSET)
#define SHADERS_MAIN_FS_DATA (SHADERS_PACKAGE + SHADERS_MAIN_FS_OFFSET)
#define SHADERS_MAIN_VS_DATA (SHADERS_PACKAGE + SHADERS_MAIN_VS_OFFSET)
#define SHADERS_MATERIAL_INPUTS_FS_DATA (SHADERS_PACKAGE + SHADERS_MATERIAL_INPUTS_FS_OFFSET)
#define SHADERS_MATERIAL_INPUTS_VS_DATA (SHADERS_PACKAGE + SHADERS_MATERIAL_INPUTS_VS_OFFSET)
#define SHADERS_POST_PROCESS_FS_DATA (SHADERS_PACKAGE + SHADERS_POST_PROCESS_FS_OFFSET)
#define SHADERS_POST_PROCESS_VS_DATA (SHADERS_PACKAGE + SHADERS_POST_PROCESS_VS_OFFSET)
#define SHADERS_POST_PROCESS_GETTERS_VS_DATA (SHADERS_PACKAGE + SHADERS_POST_PROCESS_GETTERS_VS_OFFSET)
#define SHADERS_POST_PROCESS_INPUTS_FS_DATA (SHADERS_PACKAGE + SHADERS_POST_PROCESS_INPUTS_FS_OFFSET)
#define SHADERS_POST_PROCESS_INPUTS_VS_DATA (SHADERS_PACKAGE + SHADERS_POST_PROCESS_INPUTS_VS_OFFSET)
#define SHADERS_SHADING_LIT_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADING_LIT_FS_OFFSET)
#define SHADERS_SHADING_MODEL_CLOTH_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADING_MODEL_CLOTH_FS_OFFSET)
#define SHADERS_SHADING_MODEL_STANDARD_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADING_MODEL_STANDARD_FS_OFFSET)
#define SHADERS_SHADING_MODEL_SUBSURFACE_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADING_MODEL_SUBSURFACE_FS_OFFSET)
#define SHADERS_SHADING_PARAMETERS_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADING_PARAMETERS_FS_OFFSET)
#define SHADERS_SHADING_UNLIT_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADING_UNLIT_FS_OFFSET)
#define SHADERS_SHADOWING_FS_DATA (SHADERS_PACKAGE + SHADERS_SHADOWING_FS_OFFSET)
#define SHADERS_VIGNETTE_FS_DATA (SHADERS_PACKAGE + SHADERS_VIGNETTE_FS_OFFSET)

#endif
