#ifndef FILAMENT_TEST_RESOURCES_H_
#define FILAMENT_TEST_RESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t FILAMENT_TEST_RESOURCES_PACKAGE[];
    extern int FILAMENT_TEST_RESOURCES_TEST_MATERIAL_OFFSET;
    extern int FILAMENT_TEST_RESOURCES_TEST_MATERIAL_SIZE;
}
#define FILAMENT_TEST_RESOURCES_TEST_MATERIAL_DATA (FILAMENT_TEST_RESOURCES_PACKAGE + FILAMENT_TEST_RESOURCES_TEST_MATERIAL_OFFSET)

#endif
