#ifndef GLTF_VIEWER_H_
#define GLTF_VIEWER_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t GLTF_VIEWER_PACKAGE[];
    extern int GLTF_VIEWER_DAMAGEDHELMET_OFFSET;
    extern int GLTF_VIEWER_DAMAGEDHELMET_SIZE;
    extern int GLTF_VIEWER_GROUNDSHADOW_OFFSET;
    extern int GLTF_VIEWER_GROUNDSHADOW_SIZE;
}
#define GLTF_VIEWER_DAMAGEDHELMET_DATA (GLTF_VIEWER_PACKAGE + GLTF_VIEWER_DAMAGEDHELMET_OFFSET)
#define GLTF_VIEWER_GROUNDSHADOW_DATA (GLTF_VIEWER_PACKAGE + GLTF_VIEWER_GROUNDSHADOW_OFFSET)

#endif
