#ifndef RESOURCES_H_
#define RESOURCES_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t RESOURCES_PACKAGE[];
    extern int RESOURCES_AIDEFAULTMAT_OFFSET;
    extern int RESOURCES_AIDEFAULTMAT_SIZE;
    extern int RESOURCES_BAKEDCOLOR_OFFSET;
    extern int RESOURCES_BAKEDCOLOR_SIZE;
    extern int RESOURCES_BAKEDTEXTURE_OFFSET;
    extern int RESOURCES_BAKEDTEXTURE_SIZE;
    extern int RESOURCES_POINTSPRITES_OFFSET;
    extern int RESOURCES_POINTSPRITES_SIZE;
    extern int RESOURCES_AOPREVIEW_OFFSET;
    extern int RESOURCES_AOPREVIEW_SIZE;
    extern int RESOURCES_GROUNDSHADOW_OFFSET;
    extern int RESOURCES_GROUNDSHADOW_SIZE;
    extern int RESOURCES_HEIGHTFIELD_OFFSET;
    extern int RESOURCES_HEIGHTFIELD_SIZE;
    extern int RESOURCES_SANDBOXCLOTH_OFFSET;
    extern int RESOURCES_SANDBOXCLOTH_SIZE;
    extern int RESOURCES_SANDBOXLIT_OFFSET;
    extern int RESOURCES_SANDBOXLIT_SIZE;
    extern int RESOURCES_SANDBOXLITFADE_OFFSET;
    extern int RESOURCES_SANDBOXLITFADE_SIZE;
    extern int RESOURCES_SANDBOXLITTRANSPARENT_OFFSET;
    extern int RESOURCES_SANDBOXLITTRANSPARENT_SIZE;
    extern int RESOURCES_SANDBOXLITTHINREFRACTION_OFFSET;
    extern int RESOURCES_SANDBOXLITTHINREFRACTION_SIZE;
    extern int RESOURCES_SANDBOXLITTHINREFRACTIONSSR_OFFSET;
    extern int RESOURCES_SANDBOXLITTHINREFRACTIONSSR_SIZE;
    extern int RESOURCES_SANDBOXLITSOLIDREFRACTION_OFFSET;
    extern int RESOURCES_SANDBOXLITSOLIDREFRACTION_SIZE;
    extern int RESOURCES_SANDBOXLITSOLIDREFRACTIONSSR_OFFSET;
    extern int RESOURCES_SANDBOXLITSOLIDREFRACTIONSSR_SIZE;
    extern int RESOURCES_SANDBOXSPECGLOSS_OFFSET;
    extern int RESOURCES_SANDBOXSPECGLOSS_SIZE;
    extern int RESOURCES_SANDBOXSUBSURFACE_OFFSET;
    extern int RESOURCES_SANDBOXSUBSURFACE_SIZE;
    extern int RESOURCES_SANDBOXUNLIT_OFFSET;
    extern int RESOURCES_SANDBOXUNLIT_SIZE;
    extern int RESOURCES_TEXTUREDLIT_OFFSET;
    extern int RESOURCES_TEXTUREDLIT_SIZE;
}
#define RESOURCES_AIDEFAULTMAT_DATA (RESOURCES_PACKAGE + RESOURCES_AIDEFAULTMAT_OFFSET)
#define RESOURCES_BAKEDCOLOR_DATA (RESOURCES_PACKAGE + RESOURCES_BAKEDCOLOR_OFFSET)
#define RESOURCES_BAKEDTEXTURE_DATA (RESOURCES_PACKAGE + RESOURCES_BAKEDTEXTURE_OFFSET)
#define RESOURCES_POINTSPRITES_DATA (RESOURCES_PACKAGE + RESOURCES_POINTSPRITES_OFFSET)
#define RESOURCES_AOPREVIEW_DATA (RESOURCES_PACKAGE + RESOURCES_AOPREVIEW_OFFSET)
#define RESOURCES_GROUNDSHADOW_DATA (RESOURCES_PACKAGE + RESOURCES_GROUNDSHADOW_OFFSET)
#define RESOURCES_HEIGHTFIELD_DATA (RESOURCES_PACKAGE + RESOURCES_HEIGHTFIELD_OFFSET)
#define RESOURCES_SANDBOXCLOTH_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXCLOTH_OFFSET)
#define RESOURCES_SANDBOXLIT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLIT_OFFSET)
#define RESOURCES_SANDBOXLITFADE_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITFADE_OFFSET)
#define RESOURCES_SANDBOXLITTRANSPARENT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITTRANSPARENT_OFFSET)
#define RESOURCES_SANDBOXLITTHINREFRACTION_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITTHINREFRACTION_OFFSET)
#define RESOURCES_SANDBOXLITTHINREFRACTIONSSR_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITTHINREFRACTIONSSR_OFFSET)
#define RESOURCES_SANDBOXLITSOLIDREFRACTION_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITSOLIDREFRACTION_OFFSET)
#define RESOURCES_SANDBOXLITSOLIDREFRACTIONSSR_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXLITSOLIDREFRACTIONSSR_OFFSET)
#define RESOURCES_SANDBOXSPECGLOSS_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXSPECGLOSS_OFFSET)
#define RESOURCES_SANDBOXSUBSURFACE_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXSUBSURFACE_OFFSET)
#define RESOURCES_SANDBOXUNLIT_DATA (RESOURCES_PACKAGE + RESOURCES_SANDBOXUNLIT_OFFSET)
#define RESOURCES_TEXTUREDLIT_DATA (RESOURCES_PACKAGE + RESOURCES_TEXTUREDLIT_OFFSET)

#endif
